name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  changes:
    runs-on: self-hosted
    
    outputs:
      deploy: ${{ steps.filter.outputs.deploy }}
  
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            deploy:
              - 'src/**'
              - 'server/**'
              - 'wasm/**'
              - 'Rocket.toml'
              - 'Cargo.toml'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.deploy == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack --version 0.10.1

      - name: Cache built rust dependencies
        uses: Swatinem/rust-cache@v1

      - name: Build the server
        run: sh build.sh
      
  restart:
    if: always()
    needs: [changes, deploy]
    runs-on: self-hosted
    
    steps:
      - name: Restart server
        run: sudo systemctl restart torquelearn
