name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
      - uses: Swatinem/rust-cache@v1

      - name: Build the server
        run: cargo build --release
      
      - name: Restart server
        run: sudo systemctl restart torquelearn
