name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v2

      - name: Build the server
        run: cargo build --release
      
      - name: Restart server
        run: sudo systemctl restart torquelearn
