name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Cache built rust dependencies
        uses: Swatinem/rust-cache@v1

      - name: Build the server
        run: cargo build --release
      
      - name: Restart server
        run: sudo systemctl restart torquelearn
